#!/bin/bash

NAME=$GENERATOR_PROJECTNAME
DJANGODIR=$GENERATOR_DJANGODIR
SOCKFILE=$GENERATOR_SOCKFILE
USER=$GENERATOR_USER
GROUP=$GENERATOR_GROUP
NUM_WORKERS=$GENERATOR_WORKERS
DJANGO_SETTINGS_MODULE=core.settings
DJANGO_WSGI_MODULE=core.wsgi

echo "Starting $$NAME as `whoami`"

# Activate the virtual environment
cd $$DJANGODIR
source ../bin/activate
export DJANGO_SETTINGS_MODULE=$$DJANGO_SETTINGS_MODULE
export PYTHONPATH=$$DJANGODIR:$$PYTHONPATH

# Create the run directory if it doesn't exist
RUNDIR=$$(dirname $$SOCKFILE)
test -d $$RUNDIR || mkdir -p $$RUNDIR

# Start your Django Unicorn
# Programs meant to be run under supervisor should not daemonize themselves (do not use --daemon)
exec ../bin/gunicorn $${DJANGO_WSGI_MODULE}:application \
  --name $$NAME \
  --workers $$NUM_WORKERS \
  --user=$$USER --group=$$GROUP \
  --bind=unix:$$SOCKFILE \
  --log-level=debug \
  --log-file=-
